
name = input("What is your name?")
input("")
print(f"hello{name}")
input("")
print("do you want to hear a joke?")
input("")
print("okay!")
input("")
print("what did the bee say to the sushi?")
input("")
print("wasabi")
input("")
print("did you like my joke?")
input("")
print("thanks")