print("hello today you are going to help me write a story")
input("")
animal = input("pick a animal")
input("")
name = input("now pick a name")
input("")
location = input("now pick a location")
input("")
feeling = input("pick a feeling")
input("")
sport = input("pick a sport")
input("")

print("--------------------------------------")
print("here is the story!")
print("--------------------------------------")
print(f"one day a {animal} named {name} was feeling {feeling} in {location}")
print("--------------------------------------")
print(f"so they decided to play {sport}")