print("hello today you are going to help me write a story")
input("")
animal = input("Pick a animal:")
input("")
name = input("Now pick a name:")
input("")
location = input("Now pick a location:")
input("")
feeling = input("Pick a feeling:")
input("")
sport = input("Pick a sport:")
input("")
food = input("Pick a food:")
print("--------------------------------------")
print("here is the story!")
print("--------------------------------------")
print(f"one day a {animal} named {name} that was feeling {feeling} in {location}")
print("--------------------------------------")
input("")
print(f"so they decided to play {sport}")
print("--------------------------------------")
input("")
print(f"after playing that they were hungry so they decided to eat {food}")
print("--------------------------------------")
input("")